### PR TITLE
gchq/stroom#4124 Fix NodeResultSerialiser and add node name to errors

### LINKED ISSUE #4124: Some less serious search warnings should be reclassified as info such as string truncations and the icon should reflect max severity

### LINKED ISSUE #5224: `No match found` error on dashboard
When running a dashboard the error icon in the top right is showing, and when clicked shows:

```
The following two errors have been created while running this search:
Node: <node name>
        No match found
```

This is possibly coming from a regex match in table column filtering.

### PR DESCRIPTION
**Pull request by stroomworks1876**
Fixes #4124 , fixes #5224

### CODE REVIEW

File: stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java [hunk 1]
```diff
@@ -17,13 +17,23 @@ public final class ErrorMessage {
...
+    @JsonProperty
+    private final String node;
+
     @JsonCreator
     public ErrorMessage(@JsonProperty("severity") final Severity severity,
-                        @JsonProperty("message") final String message) {
-        this.severity = severity;
+                        @JsonProperty("message") final String message,
+                        @JsonProperty("node") final String node) {
+        this.severity = severity == null ? Severity.ERROR : severity;
```
Comment (at055612) [inline stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java]: Objects.requireNonNullElse(severity, Severity.ERROR)

File: stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessages.java [hunk 2]
```diff
@@ -38,17 +38,17 @@ public boolean isEmpty() {
...
         }
         return messages;
     }
 
-    private Map<Severity, List<String>> asMap() {
+    private Map<Severity, List<ErrorMessage>> asMap() {
         return errorMessages.stream()
                 .collect(Collectors.groupingBy(ErrorMessage::getSeverity, HashMap::new,
-                        Collectors.mapping(ErrorMessage::getMessage, Collectors.toList())));
+                        Collectors.mapping(m -> m, Collectors.toList())));
```
Comment (at055612) [inline stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessages.java]: m->m   => Function.identity()

File: stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java [hunk 3]
```diff
@@ -8,7 +8,7 @@
 
 import java.util.Objects;
 
-@JsonPropertyOrder({"severity", "message"})
+@JsonPropertyOrder({"severity", "message", "node"})
```
Comment (at055612) [inline stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java]: @JsonPropertyOrder(alphabetic = true)
easier to maintain, unless we really care about the serialised order

File: stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java (hunk 1 above)
Comment (stroomdev66) [reply stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java]: Doesn't this need to be `NullSafe.requireNonNullElse(severity, Severity.ERROR)` so it works with GWT?

Comment (at055612) [reply stroom-util-shared/src/main/java/stroom/util/shared/ErrorMessage.java]: ah yes, good point, forgot it was shared
