### PR TITLE
Fix highlight positions being incorrectly calculated

### LINKED ISSUE #3199: Editor highlights are displayed incorrectly
Where there are multiple occurrences of the same highlight term, the second and subsequent terms are highlighted incorrectly.

image

### PR DESCRIPTION
**Pull request by p-kimberley**
Closes #3199

### CODE REVIEW

File: stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/text/TextPresenter.java [hunk 1]
```diff
@@ -260,9 +260,6 @@ private List<TextRange> getHighlights(final String input, final Set<String> high
                                         new DefaultLocation(lineNo, colNo),
                                         new DefaultLocation(lineNo, colNo + highlightLength - 1)); // inclusive
                                 highlights.add(hl);
-
-                                i += highlightLength;
```
Comment (at055612) [inline stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/text/TextPresenter.java:264]: I think rather than removing this you may need to add
```
colNo += highlightLenght;
```
I think `i` is being advanced by the length of the highlight to save it going over each char in the highlight when it doesn't need to.  As `i` is going up by highlightLength and colNo is just going up by one they are getting out of sync.
